### Try data outside the range for both geometric parameters and frequency

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("../test_data/patch_antenna/Patch Antenna S11 Data.csv")
X = df.drop(columns=['dB(S(1,1)) []'])

In [49]:
complete_df = pd.DataFrame(columns=X.columns)

# Create all combinations of ranges 
ranges = {}
data_cols = list(X.columns)
for column in data_cols:
    ranges[column] = X[column].unique().tolist()

In [50]:
ranges

{'inset_dist [mm]': [0.6, 1.0, 1.4],
 'L [mm]': [11.5, 12.0, 12.5],
 'sub_thick [mm]': [2],
 'W [mm]': [14.0, 14.8, 15.6],
 'W0 [mm]': [2.5, 3.0, 3.5],
 'y0 [mm]': [3.0, 3.5, 4.0, 4.5, 5.0],
 'Freq [GHz]': [4.0,
  4.08,
  4.16,
  4.24,
  4.32,
  4.4,
  4.48,
  4.56,
  4.64,
  4.72,
  4.8,
  4.88,
  4.96,
  5.04,
  5.12,
  5.2,
  5.28,
  5.36,
  5.44,
  5.52,
  5.6,
  5.68,
  5.76,
  5.84,
  5.92,
  6.0,
  6.08,
  6.16,
  6.24,
  6.32,
  6.4,
  6.48,
  6.56,
  6.64,
  6.72,
  6.8,
  6.88,
  6.96,
  7.04,
  7.12,
  7.2,
  7.28,
  7.36,
  7.44,
  7.52,
  7.6,
  7.68,
  7.76,
  7.84,
  7.92,
  8.0,
  8.08,
  8.16,
  8.24,
  8.32,
  8.4,
  8.48,
  8.56,
  8.64,
  8.72,
  8.8,
  8.88,
  8.96,
  9.04,
  9.12,
  9.2,
  9.28,
  9.36,
  9.44,
  9.52,
  9.6,
  9.68,
  9.76,
  9.84,
  9.92,
  10.0,
  10.08,
  10.16,
  10.24,
  10.32,
  10.4,
  10.48,
  10.56,
  10.64,
  10.72,
  10.8,
  10.88,
  10.96,
  11.04,
  11.12,
  11.2,
  11.28,
  11.36,
  11.44,
  11.52,
  11.6,
  11.68,
  11.76,
  11.84,
  11.92,
  12.0]}

In [51]:
# Custom overrides
ranges['inset_dist [mm]'] += [0.4, 1.6]
ranges['L [mm]'] += [11, 13]
ranges['sub_thick [mm]'] += [1, 3]
ranges['W [mm]'] += [13.2, 16.4]
ranges['W0 [mm]'] += [2, 4]
ranges['y0 [mm]'] += [2.5, 5.5]
ranges['Freq [GHz]'] += [3.84, 3.92, 12.08, 12.16]

# Try cartesian product in pandas instead https://stackoverflow.com/a/13270110/3675086
ranges_df = pd.DataFrame(ranges[X.columns[0]], columns=[X.columns[0]])
for col in complete_df.columns[1:]:
    temp_df = pd.DataFrame(ranges[col], columns=[col])
    ranges_df = ranges_df.merge(temp_df, how='cross')

In [52]:
ranges_df

,inset_dist [mm],L [mm],sub_thick [mm],W [mm],W0 [mm],y0 [mm],Freq [GHz]
0,0.6,11.5,2,14.0,2.5,3.0,4.00
1,0.6,11.5,2,14.0,2.5,3.0,4.08
2,0.6,11.5,2,14.0,2.5,3.0,4.16
3,0.6,11.5,2,14.0,2.5,3.0,4.24
4,0.6,11.5,2,14.0,2.5,3.0,4.32
...,...,...,...,...,...,...,...
1378120,1.6,13.0,3,16.4,4.0,5.5,12.00
1378121,1.6,13.0,3,16.4,4.0,5.5,3.84
1378122,1.6,13.0,3,16.4,4.0,5.5,3.92
1378123,1.6,13.0,3,16.4,4.0,5.5,12.08
1378124,1.6,13.0,3,16.4,4.0,5.5,12.16

In [53]:
print(f"Original: {df[df.columns[:-2]].drop_duplicates().shape}")
print(f"All Permutations: {ranges_df.drop_duplicates().shape}")

Original: (405, 6)
All Permutations: (1378125, 7)

In [54]:
ranges_df.shape

(1378125, 7)

In [55]:
ranges_df[(ranges_df['inset_dist [mm]'] == 0.6) & (ranges_df['L [mm]'] == 11.5) & (ranges_df['sub_thick [mm]'] == 2) & (ranges_df['W [mm]'] == 14.0) & (ranges_df['W0 [mm]'] == 2.5) & (ranges_df['y0 [mm]'] == 3.0)]

,inset_dist [mm],L [mm],sub_thick [mm],W [mm],W0 [mm],y0 [mm],Freq [GHz]
0,0.6,11.5,2,14.0,2.5,3.0,4.00
1,0.6,11.5,2,14.0,2.5,3.0,4.08
2,0.6,11.5,2,14.0,2.5,3.0,4.16
3,0.6,11.5,2,14.0,2.5,3.0,4.24
4,0.6,11.5,2,14.0,2.5,3.0,4.32
...,...,...,...,...,...,...,...
100,0.6,11.5,2,14.0,2.5,3.0,12.00
101,0.6,11.5,2,14.0,2.5,3.0,3.84
102,0.6,11.5,2,14.0,2.5,3.0,3.92
103,0.6,11.5,2,14.0,2.5,3.0,12.08
104,0.6,11.5,2,14.0,2.5,3.0,12.16

In [56]:
import joblib
model = joblib.load('../antenna_model_standardscaler.pkl')
predictions = model.predict(ranges_df)

In [57]:
predictions

array([ -0.18765769,  -0.19497   ,  -0.20439651, ...,  -0.28585213,
       -25.47708931, -25.47708931])

In [58]:
ranges_df['prediction'] = predictions

In [59]:
ranges_df[(ranges_df['inset_dist [mm]'] == 0.6) & (ranges_df['L [mm]'] == 11.5) & (ranges_df['sub_thick [mm]'] == 2) & (ranges_df['W [mm]'] == 14.0) & (ranges_df['W0 [mm]'] == 2.5) & (ranges_df['y0 [mm]'] == 3.0)]

,inset_dist [mm],L [mm],sub_thick [mm],W [mm],W0 [mm],y0 [mm],Freq [GHz],prediction
0,0.6,11.5,2,14.0,2.5,3.0,4.00,-0.187658
1,0.6,11.5,2,14.0,2.5,3.0,4.08,-0.194970
2,0.6,11.5,2,14.0,2.5,3.0,4.16,-0.204397
3,0.6,11.5,2,14.0,2.5,3.0,4.24,-0.212828
4,0.6,11.5,2,14.0,2.5,3.0,4.32,-0.223336
...,...,...,...,...,...,...,...,...
100,0.6,11.5,2,14.0,2.5,3.0,12.00,-4.274440
101,0.6,11.5,2,14.0,2.5,3.0,3.84,-0.187658
102,0.6,11.5,2,14.0,2.5,3.0,3.92,-0.187658
103,0.6,11.5,2,14.0,2.5,3.0,12.08,-4.274440
104,0.6,11.5,2,14.0,2.5,3.0,12.16,-4.274440