### Combine the 3 sets into one set with default values from parametric sweep

In [1]:
import pandas as pd
defaults = {
    "cpw_in [mm]": 2,
    "feed_l [mm]": 3.75,
    "patch_l [mm]": 3.5,
    "cpw_g [mm]": 0.18,
    "Feed_W [mm]": 1,
    "ground_w [mm]": 1,
    "patch_ground_w [mm]": 1,
    "patch_w [mm]": 4.75
}

/tmp/ipykernel_515273/1430221899.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df1 = pd.read_csv("S11_Data_Set1.csv")
df2 = pd.read_csv("S11_Data_Set2.csv")
df3 = pd.read_csv("S11_Data_Set3.csv")
combined_df = pd.concat([df1, df2, df3])

In [3]:
for k, v in defaults.items():
    combined_df[[k]] = combined_df[[k]].fillna(value=v)

In [4]:
for col_name in ["Freq [GHz]", "dB(S(1,1)) []"]:
    combined_df[col_name] = combined_df.pop(col_name)

In [5]:
combined_df

,cpw_in [mm],feed_l [mm],patch_l [mm],cpw_g [mm],Feed_W [mm],ground_w [mm],patch_ground_w [mm],patch_w [mm],Freq [GHz],"dB(S(1,1)) []"
0,1.5,3.25,3.25,0.18,1.0,1.0,1.0,4.75,11.00,-1.455338
1,1.5,3.25,3.25,0.18,1.0,1.0,1.0,4.75,11.09,-1.495640
2,1.5,3.25,3.25,0.18,1.0,1.0,1.0,4.75,11.18,-1.566487
3,1.5,3.25,3.25,0.18,1.0,1.0,1.0,4.75,11.27,-1.667701
4,1.5,3.25,3.25,0.18,1.0,1.0,1.0,4.75,11.36,-1.799854
...,...,...,...,...,...,...,...,...,...,...
7570,2.0,3.75,3.50,0.18,1.0,1.5,1.5,5.00,19.64,-3.573784
7571,2.0,3.75,3.50,0.18,1.0,1.5,1.5,5.00,19.73,-2.925513
7572,2.0,3.75,3.50,0.18,1.0,1.5,1.5,5.00,19.82,-2.792273
7573,2.0,3.75,3.50,0.18,1.0,1.5,1.5,5.00,19.91,-3.092972
7574,2.0,3.75,3.50,0.18,1.0,1.5,1.5,5.00,20.00,-4.173233

In [6]:
combined_df.to_csv("S11_Data_combined.csv")